### ISSUE TITLE
ebov - ligth grey cross on figure

### ISSUE THREAD

**Issue by bramvrancken** [phylogeography/SPREAD2#10]
when saving, there is a light grey cross on the figure. If possible, it seems best to remove this

**Comment by fbielejec** [comment]
Your probably mean graticule lines?

**Comment by bramvrancken** [comment]
first time I see this word ‘graticule’. But yes, that is indeed what I mean.

B.


On 14 Dec 2015, at 21:53, Filip Bielejec <notifications@github.com<mailto:notifications@github.com>> wrote:


Your probably mean graticule lines?

**Comment by fbielejec** [comment]
You do realise your comment is going to stay here forever, an everlasting monument of ignorance :)
I'm closing this, graticules are awesome.

**Comment by bramvrancken** [comment]
nop, I didn’t…

On 14 Dec 2015, at 21:58, Filip Bielejec <notifications@github.com<mailto:notifications@github.com>> wrote:


You do realise your comment is going to stay here forever, an everlasting monument of ignorance :)
I'm closing this, graticules are awesome.
