### ISSUE TITLE
BF - circular visualisation

### ISSUE THREAD

**Issue by bramvrancken** [phylogeography/SPREAD2#12]
perhaps offer option to pass names if possible - location1, location2 etc is not very informative

**Comment by fbielejec** [comment]
You can edit names in coordinates editor. Closing as irrelevant.

**Comment by bramvrancken** [comment]
oops, reply in wring box:

And how are people supposed to know in what order to pass the location names? Same order as in xml?

**Comment by fbielejec** [comment]
Ordering is passed from XML to the log file
