### ISSUE TITLE
HPD level in continuous tree distribution analysis

### ISSUE THREAD

**Issue by plemey** [phylogeography/SPREAD2#2]
It is hard to know/see what HPD level is selected with the slider. The log in the bottom left corner can help, but either only shows HPD levels rounded to one decimal or it indicates only such values can be select (despite the fact that you often want something like 0.95). I think that a box to specify the exact value would be more useful...

**Comment by fbielejec** [comment]
I've increased the resolution, it now goes in increments of 0.5. I like sliders, they are easier to control what kind of input goes in. If someone wants non-typical value (like 0.88  for example) he/she can use the command line. Closing.
