### ISSUE TITLE
burn-in in continuous tree distribution

### ISSUE THREAD

**Issue by plemey** [phylogeography/SPREAD2#3]
We need a box that allows entering value rather than a slider here: the 500 limit is just arbitrary and may not suffice. If you really want a slider here than we should accommodate a percentage as burn-in

**Comment by fbielejec** [comment]
This slider is "smart", i.e. it will always display values form 0 to #trees in posterior sample - 1, see: https://github.com/phylogeography/SPREAD2/blob/6609a9ba5432a798681263ea9f6e7c910cee474d/src/gui/panels/TimeSlicerPanel.java#L475. I think this should suffice, so I'm closing it. Please re-open if neccessary.
