### ISSUE TITLE
about plotting

### ISSUE THREAD

**Issue by XuexueLiu** [phylogeography/SPREAD2#30]
We have formed json file and renderers also index.html files, but when I open the html files, it showed Nothing, I feel nervous for I have plot this example file for two days, but get the empty plot. Thankyou!

**Comment by GuyBaele** [comment]
Can you let me know if the problem persists when using FireFox?

**Comment by XuexueLiu** [comment]
I am sorry, that FireFox showed the same. I also tried google chrome, neither works also. or you can send me your browser and afflications. Thankyou!

**Comment by GuyBaele** [comment]
Can you e-mail me the files I need to try and reproduce the visualisation? Is this a discrete or continuous phylogeographic reconstruction?

**Comment by XuexueLiu** [comment]
Firefox works when I restart my machine, it's interesting to show this discrete tree. Thanks !
